---
- name: >-
    {{ _k8s_cluster_name }} resources
    {%- if _k8s_namespace_name|default('') != '' %} in {{ _k8s_namespace_name }}{% endif -%}
  k8s_config:
    apply: True
    api: "{{ _k8s_cluster_api }}"
    definition: "{{ _k8s_resource_definition }}"
  loop: "{{ query('k8s_resource_definitions', _k8s_resources_item) }}"
  loop_control:
    loop_var: _k8s_resource_definition_item
    label: >-
      {{ _k8s_resource_definition.kind }}({{ _k8s_resource_definition.apiVersion }})
      {{ _k8s_resource_definition.metadata.name }}
      {%- if 'namespace' in _k8s_resource_definition.metadata %}
      in {{ _k8s_resource_definition.metadata.namespace }}
      {%- endif -%}
  vars:
    _k8s_resource_definition: >-
      {% if _k8s_namespace_name|default('') != '' -%}
      {{ _k8s_resource_definition_item
       | combine({'metadata':{'namespace': _k8s_namespace_name}}, recursive=True) }}
      {%- else -%}
      {{ _k8s_resource_definition_item }}
      {%- endif %}
