---
- name: "{{ _k8s_cluster_name }} authentication"
  k8s_auth:
    host: "{{ _k8s_cluster.api.url | default(k8s_api_url) }}"
    username: "{{ _k8s_cluster_api_username }}"
    password: "{{ _k8s_cluster_api_password }}"
    validate_certs: "{{ _k8s_cluster_api_validate_certs | bool }}"
  vars:
    _k8s_cluster_api_password: >-
      {{ _k8s_cluster.api.password | default(k8s_api_password) }}
    _k8s_cluster_api_username: >-
      {{ _k8s_cluster.api.username | default(k8s_api_username) }}
    _k8s_cluster_api_validate_certs: >-
      {{ _k8s_cluster.api.validate_certs | default(k8s_api_validate_certs) }}
  when:
  - _k8s_cluster_api_username != ''
  - _k8s_cluster_api_password != ''
  register: r_k8s_auth

- name: "{{ _k8s_cluster_name }} configuration"
  include_tasks: k8s-cluster-config.yaml
  vars:
    _k8s_cluster_api: >-
      {{ {
        'api_key': r_k8s_auth.api_key | default(_k8s_cluster.api.token) | default(k8s_api_token),
        'ca_cert':        _k8s_cluster.api.ca_cert        | default(k8s_api_ca_cert),
        'client_cert':    _k8s_cluster.api.client_cert    | default(k8s_api_client_cert),
        'client_key':     _k8s_cluster.api.client_key     | default(k8s_api_client_key),
        'host':           _k8s_cluster.api.url            | default(k8s_api_url),
        'validate_certs': _k8s_cluster.api.validate_certs | default(k8s_api_validate_certs),
        'kubeconfig':     _k8s_cluster.kubeconfig         | default(k8s_kubeconfig),
      } }}
