---
- name: "{{ _k8s_cluster_name }} resources"
  include_tasks: k8s-{{ _k8s_resources_handling }}.yaml
  loop: "{{ range(0, _k8s_cluster_resources|length) | list }}"
  loop_control:
    loop_var: _k8s_cluster_resources_idx
    label: >-
      {{ _k8s_cluster_resources_item.name
       | default(_k8s_cluster_resources_item.namespace)
       | default(_k8s_resources_handling)
      }}
  vars:
    _k8s_cluster_resources_item: "{{ _k8s_cluster_resources[_k8s_cluster_resources_idx] }}"
    _k8s_resources_item: "{{ _k8s_cluster_resources_item }}"
    _k8s_namespace_name: "{{ _k8s_cluster_resources_item.namespace | default('') }}"
    _k8s_resources_handling: >-
      {{
      'definition'         if 'definition'         in _k8s_cluster_resources_item else
      'definition'         if 'file'               in _k8s_cluster_resources_item else
      'helm-template'      if 'helm_template'      in _k8s_cluster_resources_item else
      'info'               if 'info'               in _k8s_cluster_resources_item else
      'json-patch'         if 'json_patch'         in _k8s_cluster_resources_item else
      'namespace'          if 'namespace'          in _k8s_cluster_resources_item else
      'openshift-template' if 'openshift_template' in _k8s_cluster_resources_item else
      'definition'         if 'template'           in _k8s_cluster_resources_item else
      'definition'         if 'url'                in _k8s_cluster_resources_item else
      'unknown'
      }}
  when: >-
    _k8s_cluster_resources_item.when | default('') == '' or
    lookup('test', _k8s_cluster_resources_item.when)

- name: "{{ _k8s_cluster_name }} namespaces"
  include_tasks: k8s-namespace.yaml
  loop: "{{ _k8s_cluster_namespaces | dict2items }}"
  loop_control:
    loop_var: _k8s_namespaces_item
    label: "{{ _k8s_namespace_name }}"
  vars:
    _k8s_namespace_name: "{{ _k8s_namespaces_item.key }}"
    _k8s_cluster_resources_item: "{{ _k8s_namespaces_item.value }}"
