---
- name: Update k8s_config_search_path
  set_fact:
    k8s_config_search_path: >-
      {{ k8s_config_search_path | default([])
       + k8s_config_source.config_search_path | default([])
       | map('regex_replace', '^', inventory_dir | default(playbook_dir) ~ '/')
       | list }}
  run_once: True

- name: Include vars from included config search path for {{ k8s_config_source.name }}
  include_vars:
    depth: 1
    dir: "{{ lookup('vars', 'path') }}"
    files_matching: "^[^.].*\\.(ya?ml|json)"
  loop: >-
    {{ k8s_config_source.config_search_path | default([])
     | map('regex_replace', '^', inventory_dir | default(playbook_dir) ~ '/')
     | list }}
  loop_control:
    loop_var: path
  when: path is directory
