---
#FIXME - Implement sanity check for role
#- name: Sanity Check

- name: Create source tempdir
  tempfile:
    prefix: k8s_config_source-
    state: directory
  register: _k8s_config_cache_tempdir
  when: k8s_config_cache_dir == ''
  delegate_to: localhost
  run_once: true
  changed_when: false
  check_mode: false

- name: Load configuration sources
  include_tasks: k8s-load-config-source.yaml
  loop: "{{ k8s_config_sources | reverse | list }}"
  loop_control:
    loop_var: _k8s_config_source
    label: "{{ _k8s_config_source.name }}"
  vars:
    # Source cache directory used for downloading remote sources
    _k8s_config_source_cache_dir: >-
      {{ k8s_config_cache_dir | default(_k8s_config_cache_tempdir.path, True)
       ~ '/' ~ _k8s_config_source.name }}
    # Config source base path uses cache directory for git or otherwise the
    # base_path is required
    _k8s_config_source_base_path: >-
      {% if 'git' in _k8s_config_source -%}
      {{ _k8s_config_source_cache_dir ~ '/' ~ _k8s_config_source.base_path | default('') }}
      {%- else -%}
      {{ _k8s_config_source.base_path }}
      {%- endif %}
  when: >-
    _k8s_config_source.when | default('') == '' or
    lookup('test', _k8s_config_source.when)

- name: k8s clusters
  include_tasks: k8s-cluster.yaml
  loop: "{{ k8s_clusters }}"
  loop_control:
    loop_var: _k8s_cluster
    label: "{{ _k8s_cluster_name }}"
  vars:
    _k8s_cluster_name: >-
      {{ _k8s_cluster.name | default('k8s', True) }}
    _k8s_cluster_namespaces: >-
      {{ _k8s_cluster.namespaces | default(k8s_namespaces) }}
    _k8s_cluster_resources: >-
      {{ _k8s_cluster.resources | default(k8s_resources) }}

- name: Remove source tempdir
  file:
    path: "{{ _k8s_config_cache_tempdir.path }}"
    state: absent
  when: _k8s_config_cache_tempdir.path | default('') != ''
  delegate_to: localhost
  run_once: true
  changed_when: false
  check_mode: false
